---
- name: Hello Events
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Say Hello
      condition: event.i == 2
      action:
        run_playbook:
          name: "./playbooks/hello_msg.yml"

